set(_CATKIN_CURRENT_PACKAGE "filters")
set(filters_VERSION "0.0.0")
set(filters_MAINTAINER "hhkb <hhkb@todo.todo>")
set(filters_PACKAGE_FORMAT "2")
set(filters_BUILD_DEPENDS "roscpp" "std_msgs")
set(filters_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs")
set(filters_BUILDTOOL_DEPENDS "catkin")
set(filters_BUILDTOOL_EXPORT_DEPENDS )
set(filters_EXEC_DEPENDS "roscpp" "std_msgs")
set(filters_RUN_DEPENDS "roscpp" "std_msgs")
set(filters_TEST_DEPENDS )
set(filters_DOC_DEPENDS )
set(filters_URL_WEBSITE "")
set(filters_URL_BUGTRACKER "")
set(filters_URL_REPOSITORY "")
set(filters_DEPRECATED "")